# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obrol < Formula
  desc "Obsidian Rolodex CLI to manage contacts stored as Markdown."
  homepage "https://github.com/dce/obrol"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/dce/obrol/releases/download/v0.1.0/obrol_darwin_arm64_v0.1.0.tar.gz"
    sha256 "d3d8f4c05f31724047d4e18832358fe880b40450cae97c71bad2a827ef44d8ca"

    def install
      bin.install "obrol"
    end
  end

  test do
    system "#{bin}/obrol", "--help"
  end
end
